export const USER_ID_KEY = 'USER_ID_KEY';
export const ACCESS_TOKEN_KEY = 'ACCESS_TOKEN_KEY';
export const REFRESH_TOKEN_KEY = 'REFRESH_TOKEN_KEY';
export const PUSH_UP_WORKOUT_LEVEL = 'PUSH_UP_WORKOUT_LEVEL';
export const SQUAT_WORKOUT_LEVEL = 'SQUAT_WORKOUT_LEVEL';
export const SIT_UP_WORKOUT_LEVEL = 'SIT_UP_WORKOUT_LEVEL';
